### ISSUE TITLE
conform to vimwiki Todo list conventions

### ISSUE THREAD

**Issue by linuxcaffe** [tbabej/taskwiki#12]
Wherever possible, vimwiki Todo list key-mappings and behavior should be adopted for taskwiki. 

(from vimwiki.txt)
<pre>
Todo lists                                                vimwiki-todo-lists
------------------------------------------------------------------------------

You can have todo lists -- lists of items you can check/uncheck.

Consider the following example: >
 = Toggleable list of todo items =
   * [X] Toggle list item on/off.
     * [X] Simple toggling between [ ] and [X].
     * [X] All list's subitems should be toggled on/off appropriately.
     * [X] Toggle child subitems only if current line is list item
     * [X] Parent list item should be toggled depending on it's child items.
   * [X] Make numbered list items toggleable too
   * [X] Add highlighting to list item boxes
   * [X] Add [ ] to the next list item created with o, O and CR.

Pressing  C-Space  on the first list item will toggle it and all of its child
items: >
 = Toggleable list of todo items =
   * [ ] Toggle list item on/off.
     * [ ] Simple toggling between [ ] and [X].
     * [ ] All of a list's subitems should be toggled on/off appropriately.
     * [ ] Toggle child subitems only if the current line is a list item.
     * [ ] Parent list item should be toggled depending on their child items.
   * [X] Make numbered list items toggleable too.
   * [X] Add highlighting to list item boxes.
   * [X] Add [ ] to the next list item created using o, O or CR.

Pressing C-Space on the third list item will toggle it and adjust all of its
parent items: >
 = Toggleable list of todo items =
   * [.] Toggle list item on/off.
     * [ ] Simple toggling between [ ] and [X].
     * [X] All of a list's subitems should be toggled on/off appropriately.
     * [ ] Toggle child subitems only if current line is list item.
     * [ ] Parent list item should be toggled depending on it's child items.
   * [ ] Make numbered list items toggleable too.
   * [ ] Add highlighting to list item boxes.
   * [ ] Add [ ] to the next list item created using o, O or CR.

Parent items should change when their child items change. If not, use
vimwiki_glr. The symbol between [ ] depends on the percentage of toggled
child items (see also g:vimwiki_listsyms): >
    [ ] -- 0%
    [.] -- 1-33%
    [o] -- 34-66%
    [O] -- 67-99%
    [X] -- 100%

It is possible to toggle several list items using visual mode. But note that
instead of toggling every item individually, all items get checked if the
first item is unchecked and all items get unchecked if the first item is
checked.

Use gl Space (see vimwiki_gl Space) to remove a single checkbox and
gLSpace (see vimwiki_gL Space) to remove all checkboxes of the list the
cursor is in.
</pre>

**Comment by tbabej** [comment]
This should just work. Taskwiki complements vimwiki, so you are supposed to have vimwiki among your plugins too.

**Comment by tbabej** [comment]
If any of the vimwiki's functionality does not work with taskwiki, let me know. Closing as too general and invalid.
