### ISSUE TITLE
Ambiguous dependency rules

### ISSUE THREAD

**Issue by xxmissingnoxx** [tbabej/taskwiki#245]
Problem:
After running some experiments, it seems as though the rules around dependencies in TaskWiki are a bit ambiguous (or maybe hidden from the user?). If 2 top level elements are dependent on the same child element (with the same hash too), what should happen when you check or uncheck one of the boxes?

Example:

* [ ] Go to Munich  #5850c10d
    * [ ] Learn German  #7126fd7b
    * [S] Research Munich  #11331075
* [ ] Go to Berlin  #a3f4c2da
    * [ ] Learn German  #7126fd7b

Assume that the second variation of learn German was added to TaskWarrior first (original). 

- If the original (Berlin) is checked, the second copy will be checked upon save.
- If both are checked, and the original is unchecked, both will be  unchecked on save.

They both have the exact same hash (copied the line to create the Munich variant). There is some sort of difference between the 2 instances because TaskWiki is following the lead of the original checkbox. It's not clear what makes them different in the obvious data available. Using <CR> on either entry yields the same information. What is it about the implementation of TaskWiki that allows it to differentiate between the two when they have the same hash and present the same data? What's the best way of checking or unchecking a task and making sure that it ripples across all instances (i.e. saves to underlying Taskwarrior data)? Is this behavior intentional and I'm not understanding the semantics? I didn't see anything in the documentation.

Relevant resources:
I've looked at [this issue](https://github.com/tbabej/taskwiki/issues/149) and am trying to get a better understanding of how dependencies work.
