### ISSUE TITLE
more gracefully handle "broken" ViewPorts

### ISSUE THREAD

**Issue by linuxcaffe** [tbabej/taskwiki#54]
I'm working with the excellent vim-template (https://github.com/aperezdc/vim-template) in opening project.wiki and diary files, and it's working nicely! The issue here is that the template files use the same extension (*.project.wiki) and vim opens it as a wiki file (https://gist.github.com/linuxcaffe/31177ef020856e49e91e) and taskwiki (correctly) sees it as horribly broken (https://gist.github.com/linuxcaffe/efb71b3643ac9e889369)

I hope to continue using these templates, and am looking for a fix/ workaround/ simpler error message.

**Comment by linuxcaffe** [comment]
FYI, the product of that template looks like this;
<pre>
_Manse project wiki file_ -- manse.project.wiki -- created: 2015-04-03 22:59

Project Name	:: Manse
Description	:: the Presbyterian Manse
Client		:: 
Manager		:: djp

== Tasks ==
=== Manse Pending Tasks | +PENDING project:manse | area:home ===
* [ ] install low-watt lighting  #c9600278
* [ ] install video security  #afb03b75
* [ ] install hot water insulation  #15426dea
* [ ] asume utility bills (2015-03-20 00:00)  #b1c4de8b
* [ ] renovate manse  #fe765047
* [ ] install sound system  #6e795fde
* [ ] clean eaves-troughs  #3eb25e5a
* [ ] wash windows  #6d46ddcc
=== Manse Waiting Tasks | +WAITING project:manse ===
=== Manse Completed Tasks | +COMPLETED project:manse | status:completed ===
* [X] dissassemble desk (2014-06-30 23:59)  #7e5be351
* [X] pick up Uhaul 26ft truck !!! (2014-07-03 00:00)  #88e77d77
* [X] buy second air filter for koi pond (2014-06-23 00:00)  #7d75f23b
* [X] fix pond pump (2014-06-23 00:00)  #ffe4c0c7
* [X] pack china credenza (2014-06-30 23:59)  #32a6d31b
* [X] call Kevin (2014-06-20 05:07)  #53f0f219
== Manse Scope ==
== Manse Outcomes ==
== Manse People ==
- Barb Bateman
- Rob Price
- Kevan Doucette
- Jim Wikens
== Manse Financial ==
== Manse Notes ==
# 
# vim: foldlevel=2
</pre>

**Comment by tbabej** [comment]
Are you required to use the same extension?

As a workaround, you can probably define a simple empty variable, and put it at the beginning of the viewport definition line.

    %SOMETHINGEMPTY%=== %CLASS% Completed Tasks | +COMPLETED project:%FILE% | status:completed ===

**Comment by linuxcaffe** [comment]
This is fixed, or at least worked around, in the lates taskwiki updates PROVIDING the related headings are deliberately "disabled" with a leading, nul value. If that makes no sense, see the following:
<pre>
%NUL%== Tasks Due Today | due:%date% ==
%NUL%== Tasks Completed Today | end:%date% | status:completed ==
%NUL%== Calls to Make | +PENDING desc.startswith:call or +call | + call ==
%NUL%== Things To Get | +PENDING desc.startswith:get or desc.startswith:pickup or +get | +get ==
</pre>

Also the following vim-template-user-function needs to be in .vimrc:
<pre>
let g:templates_user_variables = [['NUL', 'GetNul']]
function GetNul()
    return expand('')
endfunction
<pre>
the %NUL% is expanded to nothing!
