### ISSUE TITLE
Can't create links for todo items

### ISSUE THREAD

**Issue by ghost** [tbabej/taskwiki#88]
I'm not sure if this is expected behavior, but when I create a task out of a link, the link disappears, and when I put brackets on a task, it doesn't create a link. It might be some config issue with Vundle and taskwiki.

**Comment by jamesmlees** [comment]
Same for me. I think I'd find this quite useful.

**Comment by tbabej** [comment]
Are you guys talking about vimwiki links, or regular markdown links? Maybe an example would be helpful to illustrate.

**Comment by jamesmlees** [comment]
Can't speak for ghost, but I'm talking about vimwiki links. As an example. Consider the following snippet
```
# Wiki List
* Some Wiki Item

# Task List
* [ ] Some task item  #559cdeaa
```

If I visually select `Some Wiki Item` and `<CR>`, `Some Wiki Item` becomes a wiki link to `$WIKIPATHi/Some Wiki Item.wiki`

```
# Wiki List
* [[Some Wiki Item]] 
```

If I visually select `Some task item` and `<CR>`, the item is wrapped in square brackets, correctly, but vimwiki doesn't acknowledge it's a link, and displays the `[[]]` [see screengrab](http://imgur.com/kFY17mX).
Similarly, if I prepend square brackets to the wiki item the same behaviour is exhibited.

```
# Wiki List
* [ ] [[Some Wiki Item]]

# Task List
* [ ] [[Some task item]]
```

Does this make sense? It's very much a 'nice-to-have' for me.

Wanted to say a big thankyou for this tool though, it's something I've been looking for for quite some time 👏👏👏

**Comment by tbabej** [comment]
There are two problems I see:

1. concealment (double brackets shown, while they should be hidden)
2. Enter does not work for this kind of a link

1.) Could be worked out, I think.
2.) Taskwiki overrides the <CR> mapping for links to show the task info, while underlying vimwiki uses that for links. Simplest solution would be to additionally map :VimwikiFollowLink to some other key / key combination, and use that for links in tasks.

**Comment by tbabej** [comment]
Okay, I solved and pushed the syntax issue. The rest can be worked out by a custom mapping for :VimwikiFollowLink (you can try that typing the :VimwikiFollowLink command works already), but beware that your tasks will be displayed as [[content]] inside taskwarrior, i.e.:

    ID Age   Project     Description        Urg
    14 18min Testproject [[Some task item]]    0

**Comment by jamesmlees** [comment]
That's awesome! Thanks so much for that, will look into the custom mappings later on. 👌

**Comment by tbabej** [comment]
No need for a custom mapping anymore, I implemented smarter algorithm for deciding whether to follow a link, or inspect a taskwiki object. Cursor standing inside a link will now always cause the link to be followed.

**Comment by jamesmlees** [comment]
This is fantastic. Thanks very much!
